# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
# Let us list the factors of the first seven triangle numbers:
# 1: 1
# 3: 1,3
# 6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.
# What is the value of the first triangle number to have over five hundred divisors?
i = 1
while i > 0:
    tri_number = 0
    counter = 0
    for j in range(1, i+1):
        tri_number = tri_number + j
    for k in range(1, tri_number + 1):
        if tri_number%k == 0:
            counter = counter + 1
    print("triangle number ", tri_number, "counter  =", counter, "i value", i)
    if counter >= 500:
        print(tri_number)
        break
    i = i+1

print(tri_number)


# Actual output is 76576500 and the i value is 12375